apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Values.database.host }}"
            - name: WORDPRESS_DB_USER
              value: "{{ .Values.database.user }}"
            - name: WORDPRESS_DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.database.name }}"

