apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: mysql
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-02-06T08:52:53Z"
  labels:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: mysql-0.1.0
  name: mysql
  namespace: default
  resourceVersion: "700"
  uid: c6e2ddf7-d396-4a8c-aa4b-ced198e9a231
spec:
  clusterIP: 10.105.97.95
  clusterIPs:
  - 10.105.97.95
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3306
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/name: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
