name: CI Pipeline for WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACR_NAME: #--------------Pending----------------------
  IMAGE_NAME: wordpress-custom

jobs:
  lint:
    name: Lint YAML & Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint YAML Files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint

      - name: Lint Helm Chart
        run: helm lint helm/wordpress

  security_scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.45.0_Linux-64bit.tar.gz
          tar -xvzf trivy_0.45.0_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Dockerfile
        run: trivy fs --severity HIGH,CRITICAL .

  build_and_push:
    name: Build & Push Docker Image to ACR
    runs-on: ubuntu-latest
    needs: [lint, security_scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: #-------------------Pending-------------------------

      - name: Set Up Docker
        run: |
          az acr login --name $ACR_NAME
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
      
      - name: Push Docker Image to ACR
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Trigger CD Pipeline
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/cd.yml/dispatches \
          -d '{"ref": "main"}'
